---
title: "Methods"
format: docx
editor: visual
bibliography: references.bib
---

## Strata-free estimates

Partners in Flight (PIF) estimate bird populations within geo-political regions based on summaries of counts on all North American Breeding Bird Survey (BBS) routes within each region. Summarising observed counts on BBS routes across these regions assumes that the BBS routes are a representative sample of the region. This assumption is reasonable for many species and many regions, but not all. With the development of new spatial information on the paths of BBS routes and range-wide relative abundance surfaces for many species from eBird ([@fink]), this assumption is no longer necessary. Instead of summarising BBS observations within broad scale geo-political strata (e.g., Bird Conservation Regions by political jurisdictions), we can use the relationship between observed counts on each route and the relative abundance surface within in the area immediately surrounding each BBS route to account for the sampling bias in the BBS roadside surveys. It is relatively trivial to assume that the BBS observations are a representative sample of the birds, habitats, and land area within a short buffer (e.g.,400 m radius) of the route paths.

## eBird relative abundance

We calculated the area weighted mean of the eBird relative abundance cell values within the buffer zone of route-j ($I_{ebird_{r}}$) to use as a predictor on the observed BBS counts at that route.

$$ I_{ebird_{r}} = \frac{\sum_{i=1}^{i=c_r}MeanWeeklyRelativeAbundance_{i}*a_i}{\sum_{i=1}^{i=c_r}a_{i}} $$

We used the mean weekly relative abundance values for the weeks that overlap the BBS field season. We explored alternative summaries of the eBird relative abundance surfaces including the seasonal medians, and maximum relative abundance within the BBS field season [@stillman2023]. We chose to use means of weeks within the BBS field season because these showed the most consistent and linear relationships to the observed BBS counts when compared across many species.

We included all routes on which the species was observed during BBS surveys in the last 10 years of observations (2013 - 2023, excluding 2020 when the BBS was cancelled) and that overlapped positive values of the eBird relative abundance surface. We also excluded the BBS routes where the mean relative abundance values fell in the lowest 10% of the relative abundance values because for some species and routes these very low value predictors generated some extreme predictions and convergence failures.

The relationship between the counts on BBS routes and the eBird relative abundances within these route path buffers along with the PIF population estimates approach to scaling BBS counts to total population size, provide the logical stepping stones to calibrate the eBird relative abundance values to represent a density of birds.

## Proportional relative abundance

Both the BBS counts and the values of the eBird weekly abundance surfaces are designed to represent an index of abundance; i.e., relative abundance, abundance at one location, relative to other locations. For the BBS, the methodological controls in the survey protocol ensure that the observed counts represent relative abundance of the birds in the areas adjacent to the road ($C_{bbs}$), and the analytical adjustments in the eBird analyses generate estimates of weekly or seasonal relative abundance across a species' range ($I_{ebird}$). These indices of abundance are by definition, proportional to true abundance ($N$), and so each index has some associated proportionality constant ($a_{bbs}$ or $a_{ebird}$).

$$
N = \frac{C_{bbs}}{a_{bbs}}
$$ $$
N = \frac{I_{ebird}}{a_{ebird}}
$$ The PIF population estimation equation [@stanton2019] represents one estimate of the BBS proportionality constant $a_{bbs}$, i.e., a factor that scales the observed counts by BBS observers to true abundance. Combining the equations above, it becomes clear that because each index is proportional to true abundance, there is also a proportional relationship between the two indices and their proportionality constants. $$
N = \frac{C_{bbs}}{a_{bbs}}  = \frac{I_{ebird}}{a_{ebird}} 
$$ Further re-arranging suggests a relationship for predicting the BBS counts based on the ebird abundance indices and the quotient of their two proportionality constants.

$$
{N}*{a_{bbs}} = C_{bbs}  = I_{ebird}*\frac{a_{bbs}}{a_{ebird}}
$$ This quotient of two constants, is itself a constant, which here we refer to as ($B = \frac{\alpha_{bbs}}{\alpha_{ebird}}$).

$$
{N}*{a_{bbs}} = I_{ebird}*B = C_{bbs}
$$ So finally, the right side of this equation gives the basis for estimating $B$ using the relationship between the ebird relative abundance surface and the observed BBS counts. Then once we have an estimate of $B$, we can then combine it with $\frac{1}{\alpha_{bbs}}$ to estimate the true abundance of birds across the landscape. This term $\frac{1}{\alpha_{bbs}}$ is just a re-expression of the PIF population estimates equation that translates counts on BBS routes to true abundance. Therefore, multiplying these two terms together $B* \frac{1}{\alpha_{bbs}}$ generates a calibration factor to scale from the eBird estimated relative abundance to true total abundance in a grid cell. $$
{N} = I_{ebird}*B*\frac{1}{{a_{bbs}}}
$$

## Estimating the relationship between BBS counts and eBird relative abundance

We fit a Bayesian hierarchical model that estimates the $B$ term in the above equation. We modeled the expected count during each BBS as a function of the log-transformed mean eBird relative abundance values within a 400 m buffer surrounding the BBS route-path. The model also accounts for: 1) the variation among BBS routes and observers, 2) the variation among years; 3) the seasonal variation during the period of acceptable BBS survey conditions and how that seasonal pattern varies among BBS strata.

We log transformed the area weighted mean relative abundance values at each BBS route and used them as an offset in a log-link model that predicts each observed BBS count ($C_{r,t}$) on route-j, in year-t. Treating these $log(I_{ebird_{r}})$ as an offset respects the multiplicative relationship derived above.

$$
log(C_{bbs}) = log(I_{ebird}*B) = log(I_{ebird}) + log(B)
$$

This assumes a linear relationship with a slope of 1 between the log of the eBird relative abundance surface and the log of the observed BBS counts. This assumption is explicit if each relative abundance value is proportional to true abundance, but also necessary so that the final population estimates respect the spatial distribution in the eBird relative abundance surface. Of course, either or both set of estimates may include errors and therefore fail to meet the assumption of relative abundance in important ways beyond what we have accounted for here. Exploring those possible failures is beyond the scope of this work, but it will include assessing the slope for each species and for different summaries of the eBird relative abundance surface (e.g., the mean, median, or maximum seasonal abundance, and the weeks included in the season to match the BBS observations).

We modeled the observed BBS counts in a similar way to many of the common status and trend models for the BBS [@smith2024] as realizations of a negative binomial distribution with mean $\lambda_{j,r,d,t,s}$ and inverse dispersion parameter $\phi$.

$$
C_{j,r,d,t,s} \sim NegativeBinomial(\lambda_{j,r,d,t,s},\phi) 
$$

$$
log(\lambda_{j,r,d,t,s}) = \beta_{r} + \delta_{d,s} + \gamma_{s,t} + \omega_j + log(I_{ebird_{r}})
$$

In this model formulation, the intercept ($\beta_{r}$) represents a scaling factor between the observed BBS counts on route-r, and the eBird relative abundance for route-r, after accounting for the variation due to the year-t ($\gamma_{s,t}$), and day of the BBS season-d in stratum-s ($\delta_{d,s}$). We used a hierarchical structure to model the variation in the scaling factor among routes $\beta_{r}\sim t(\nu,\bar{B},\sigma_{B})$, while accounting for the repeated observations on each route by a given observer $\omega_{j}\sim \operatorname{Normal}(0,\sigma_{\omega})$. The hyperparameter $\bar{B}$ represents the mean log-scale eBird-BBS scaling factor across all routes. We used a t-distribution to allow the variation among routes to have heavier tails than the normal and to provide a robust estimator that is less sensitive to extreme outliers (e.g., routes with unusually high or low counts).

The year-term was fit as a random-walk time-series, centered on the year of the relative abundance surface (i.e., $\Gamma_{2022} = 0$ for the eBird status and trends version 2023).

$$
\begin{aligned}
\Gamma_{t|t<2022} &\sim \operatorname{Normal}(\Gamma_{t+1},\sigma{\Gamma}) \\
\Gamma_{t|t>2022} &\sim \operatorname{Normal}(\Gamma_{t-1},\sigma{\Gamma})  \\
\end{aligned}
$$

This specific centering ensures that the mean calibration ($B$) matches the year of the eBird relative abundance surface, and that the model can adjust for non-linear population trends of each species while using information from many years of BBS observations. We then allowed this random-walk time-series to vary in space (for all years except 2022, when it remained fixed at 0), by grouping BBS routes by strata-s, defined by the spatial intersections of Province, State, and Territory boundaries with the North American Bird Conservation Regions ([@smith2024a]). A spatially explicit hierarchical structure was used to estimate strata-specific $\gamma_{s,t}$ using the same intrinsic conditional autoregressive (iCAR) parameterisation used to model strata-level variation in the spatial variant of the first-difference model of the r-package *bbsBayes2* ([@edwards2023]), following Smith et al. (2024a). For example, in the year 2021, the difference from the centered year 2022 in stratum-s was,

$$
\gamma_{s,2021} \sim \Gamma_{2021} + \operatorname{Normal}(\frac{\sum_{k=1}^{N_s} \gamma_{k,2021}}{N_s},\frac{\sigma_{\gamma}}{N_s}).
$$

The seasonal variation was modeled as a hierarchical GAM smooth term that adjusts for the variation in the day each BBS survey was conducted. We used the hierarchical GAM to smooth the variation in counts across the BBS season while allowing the shape of that seasonal smooth to vary across the species' range and still shrink towards the mean seasonal pattern of neighbouring strata when data were relatively sparse ([@pedersen2019][@smith2021][@smith2024a]). To model that spatial variation in the seasonal component, the hierarchical GAM smooths were fit using the same iCAR parameterisation used to model annual smooth terms in spatial variants of the GAM and GAMYE models in the r-package *bbsBayes2* ([@edwards2023]), following Smith et al. (2024).

To account for the asymmetries of the log-scale retransformation (i.e., $\mathrm{E}(exp(B)) \neq exp(\mathrm{E}(B))$) and some extreme tails in the distribution of the route-level $\beta_r$ terms, we used a retransformation approach that does not assume a log-normal distribution, following (Duan 1983). We first excluded the routes on the extreme tails of the distribution of route-level $\beta_r$ values (values outside of the middle 95% of the distribution). We then calculated the retransformed calibration value for each of the remaining-R 95% of the routes and averaged across these routes to estimate the calibration factor ($B$).

$$Calibration = B = 1/R * \sum^{R}_{r = 1}{\frac{exp(\beta_r) * C_p * C_t}{area}}$$

We chose to use a trimmed mean calculation across the collection of routes included in the analysis so the mean value would be less sensitive to some extreme tails of these route-level distributions. These extreme values often reflected routes with relatively low estimated relative abundance but with a relatively high count of birds during at least one BBS.

We can then combine the posterior draws of the scaling factor $B$, with Monte Carlo processes similar to those used in @stanton2019 to propagate the uncertainty of the scaling factor with the estimates of adjustment factors that match BBS observation conditions. The re-scaling to represent density accounts for: 1) the estimated availability of birds for detection (and its uncertainty) during a 3-minute BBS point count conducted on an average BBS survey day; 2) the estimated detectability distance for roadside counts and the uncertainty in its estimate; and 3) a correction factor used in previous PIF population estimates to account for the bias in the detectability between male and female birds of each species [@stanton2019].

In this calibration, $area = \frac{(50 * \pi * \mathcal{N}(EDR,\sigma_{EDR})^2)}{10^6}$ the area in square kilometers surveyed by a 50-stop BBS route, based on the estimated Effective Detection Radius (EDR) for a roadside count from the NA-POPS project [@edwards2023]. We incorporated the uncertainty of the EDR estimate into each sample of the posterior distribution, by making a random draw from a normal distribution with the mean and standard deviation based on the estimated mean and standard error of the mean from the NA-POPS analyses. We selected the EDR estimates from the better supported of either the roadside model or the null model in the most recent estimates from NA-POPS.

The time of day correction $C_t$ in this model was based on the estimated availability from the best supported removal model in the NA-POPS analyses. Availability represents the probability that a bird is available for detection during a 3-minute BBS count $p_{avail}$. The inverse of that probability represents an estimate of the multiplicative correction factor necessary to account for the proportion of birds that were present, but not available for detection during that time $C_t \sim \frac{1}{\mathcal{N}(p_{avail} , \sigma_{p_{avail}})}$. We drew independent random samples from a normal distribution centered on $p_{avail}$ for each posterior sample, and constrained the normal distribution to values between 0.001 and 0.999 to avoid impossible probabilities.

Finally, the pair correction factor was incorporated based on the correction for the ratio of the observed proportion of birds that are female to the expected 0.5 (assuming an even sex ratio in the population). These values can be calculated based as either $C_p = 2-(p_{female}/0.5)$, or following the values used in previous analyses (Stanton et al.. 2019, truncated normal distribution with a mean equal to the species' assigned pair correction value, standard deviation equal to 0.13, and truncated at 1.0 and 2.0).

This calibration factor mutliplied by an eBird relative abundance value in a given cell, represents an estimated number of birds per $km^2$.

For each regional estimated population, we calculated the summed relative abundance values within the region, then multiplied that summed relative abundance by each posterior draw of the calibration factor, and acountted for the area of each cell (e.g., for the 3km cells in the highest resolution seasonal abundance surfaces 9 $km^2$). Variation across all posterior draws provides an estimate of the uncertainty of the population size estimate.

## Comparisons with the existing estimation approach

We compared the estimated populations from this model to those derived from the existing modeling process (following Stanton et al. 2019), for a selection of species to highlight some of the key benefits and challenges of this approach. We chose a selection of species classified as resident and migratory for the purposes of their estimated eBird relative abundance surfaces.

We compared the estimates on the finest spatial resolution available for the existing modeling process: the analytical strata represented by the intersection of political jurisdictions (provinces, states, and territories) with the Bird Conservation Regions (BCRs). At that fine scale, we predicted that the differences in population estimates would be largely based on two factors: the relative-abundance sampling bias of the BBS routes relative to the stratum, and the interaction between the relative abundance in each stratum and the temporal trend in abundance over the 10-year span of BBS observations included in the calculations.

We estimated the sampling bias of the BBS by calculating a ratio of the mean relative abundance values that overlap the BBS route-paths over the mean relative abundance values across the entire stratum. Strata with positive bias by the BBS (where the BBS routes sample high abundance areas relative to the stratum), our model should generate lower estimates of population size than the existing analytical process. Strata with negative bias by the BBS (where the BBS routes sample relatively low abundance areas), we expect higher estimates of population size.

We also estimated the ratio of the mean predicted abundance in each stratum and each year, with the predicted abundance in the year of the eBird relative abundance surface. The existing esimation process estimates a ten-year average population (e.g., the average over the 2013-2021 period). This ratio of the predicted counts in 2022 over the mean of the predicted counts in all years, reflects the average expected change in the population estimates due to the local population trend. For example, in a stratum where the time-series of observations from the BBS suggest a decline over the period 2013-2023, estimated populations from the new model will be lower to adjust for that ongoing trend.
